// Code generated by Kitex v0.11.3. DO NOT EDIT.
package userservice

import (
	server "github.com/cloudwego/kitex/server"
	kuser "github.com/gwen0x4c3/easy_note/kitex_gen/kuser"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler kuser.UserService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler kuser.UserService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
