// Code generated by Kitex v0.11.3. DO NOT EDIT.

package noteservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	knote "github.com/gwen0x4c3/easy_note/kitex_gen/knote"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateNote": kitex.NewMethodInfo(
		createNoteHandler,
		newNoteServiceCreateNoteArgs,
		newNoteServiceCreateNoteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteNote": kitex.NewMethodInfo(
		deleteNoteHandler,
		newNoteServiceDeleteNoteArgs,
		newNoteServiceDeleteNoteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateNote": kitex.NewMethodInfo(
		updateNoteHandler,
		newNoteServiceUpdateNoteArgs,
		newNoteServiceUpdateNoteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"MGetNote": kitex.NewMethodInfo(
		mGetNoteHandler,
		newNoteServiceMGetNoteArgs,
		newNoteServiceMGetNoteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryNote": kitex.NewMethodInfo(
		queryNoteHandler,
		newNoteServiceQueryNoteArgs,
		newNoteServiceQueryNoteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	noteServiceServiceInfo                = NewServiceInfo()
	noteServiceServiceInfoForClient       = NewServiceInfoForClient()
	noteServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return noteServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return noteServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return noteServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "NoteService"
	handlerType := (*knote.NoteService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "knote",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.11.3",
		Extra:           extra,
	}
	return svcInfo
}

func createNoteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knote.NoteServiceCreateNoteArgs)
	realResult := result.(*knote.NoteServiceCreateNoteResult)
	success, err := handler.(knote.NoteService).CreateNote(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newNoteServiceCreateNoteArgs() interface{} {
	return knote.NewNoteServiceCreateNoteArgs()
}

func newNoteServiceCreateNoteResult() interface{} {
	return knote.NewNoteServiceCreateNoteResult()
}

func deleteNoteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knote.NoteServiceDeleteNoteArgs)
	realResult := result.(*knote.NoteServiceDeleteNoteResult)
	success, err := handler.(knote.NoteService).DeleteNote(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newNoteServiceDeleteNoteArgs() interface{} {
	return knote.NewNoteServiceDeleteNoteArgs()
}

func newNoteServiceDeleteNoteResult() interface{} {
	return knote.NewNoteServiceDeleteNoteResult()
}

func updateNoteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knote.NoteServiceUpdateNoteArgs)
	realResult := result.(*knote.NoteServiceUpdateNoteResult)
	success, err := handler.(knote.NoteService).UpdateNote(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newNoteServiceUpdateNoteArgs() interface{} {
	return knote.NewNoteServiceUpdateNoteArgs()
}

func newNoteServiceUpdateNoteResult() interface{} {
	return knote.NewNoteServiceUpdateNoteResult()
}

func mGetNoteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knote.NoteServiceMGetNoteArgs)
	realResult := result.(*knote.NoteServiceMGetNoteResult)
	success, err := handler.(knote.NoteService).MGetNote(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newNoteServiceMGetNoteArgs() interface{} {
	return knote.NewNoteServiceMGetNoteArgs()
}

func newNoteServiceMGetNoteResult() interface{} {
	return knote.NewNoteServiceMGetNoteResult()
}

func queryNoteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knote.NoteServiceQueryNoteArgs)
	realResult := result.(*knote.NoteServiceQueryNoteResult)
	success, err := handler.(knote.NoteService).QueryNote(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newNoteServiceQueryNoteArgs() interface{} {
	return knote.NewNoteServiceQueryNoteArgs()
}

func newNoteServiceQueryNoteResult() interface{} {
	return knote.NewNoteServiceQueryNoteResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateNote(ctx context.Context, req *knote.CreateNoteRequest) (r *knote.CreateNoteResponse, err error) {
	var _args knote.NoteServiceCreateNoteArgs
	_args.Req = req
	var _result knote.NoteServiceCreateNoteResult
	if err = p.c.Call(ctx, "CreateNote", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteNote(ctx context.Context, req *knote.DeleteNoteRequest) (r *knote.DeleteNoteResponse, err error) {
	var _args knote.NoteServiceDeleteNoteArgs
	_args.Req = req
	var _result knote.NoteServiceDeleteNoteResult
	if err = p.c.Call(ctx, "DeleteNote", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateNote(ctx context.Context, req *knote.UpdateNoteRequest) (r *knote.UpdateNoteResponse, err error) {
	var _args knote.NoteServiceUpdateNoteArgs
	_args.Req = req
	var _result knote.NoteServiceUpdateNoteResult
	if err = p.c.Call(ctx, "UpdateNote", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MGetNote(ctx context.Context, req *knote.MGetNoteRequest) (r *knote.MGetNoteResponse, err error) {
	var _args knote.NoteServiceMGetNoteArgs
	_args.Req = req
	var _result knote.NoteServiceMGetNoteResult
	if err = p.c.Call(ctx, "MGetNote", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryNote(ctx context.Context, req *knote.QueryNoteRequest) (r *knote.QueryNoteResponse, err error) {
	var _args knote.NoteServiceQueryNoteArgs
	_args.Req = req
	var _result knote.NoteServiceQueryNoteResult
	if err = p.c.Call(ctx, "QueryNote", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
